#!/bin/sh

curl --request POST --url http://localhost:$1/v1/topdf  --output html-pdf-test.pdf --header 'Content-Type: text/html' --data '<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>HTML to PDF</title>
        <style type="text/css">
            @page {
                size: A4 portrait;
                margin: 0.5cm;
            }
        </style>
    </head>
    <body>
        <div style="text-align: center">
            <h1>HTML to PDF Test</h1>
        </div>
        <div style="margin: 4px; padding: 6px; background-color: #0a5c20; color: white; border-radius: 10px; font-size: 14pt;">
            <p>This is a test</p>
        </div>
    </body>
</html>'
